import type { Lesson } from "@/lib/types";

export const unit4Lessons: Lesson[] = [
  {
    id: "u4-l1",
    unitId: "unit-4",
    number: 13,
    title: "-are Verbs",
    titleIt: "Verbi in -are",
    summary: "Conjugate regular -are verbs in the present tense.",
    objectives: [
      "Conjugate parlare, mangiare, lavorare",
      "Use subject pronouns when needed",
      "Build simple present sentences",
    ],
    vocabulary: [
      { it: "parlare", en: "to speak" },
      { it: "mangiare", en: "to eat" },
      { it: "lavorare", en: "to work" },
      { it: "abitare", en: "to live (reside)" },
      { it: "studiare", en: "to study" },
      { it: "ascoltare", en: "to listen" },
      { it: "guardare", en: "to watch / look at" },
      { it: "io parlo", en: "I speak" },
      { it: "tu parli", en: "you speak" },
      { it: "lui/lei parla", en: "he/she speaks" },
    ],
    grammar: [
      {
        title: "Present of -are verbs",
        explanation:
          "Drop -are and add: -o, -i, -a, -iamo, -ate, -ano. Subject pronouns are optional because the ending shows the person.",
        examples: [
          { it: "Parlo italiano.", en: "I speak Italian." },
          { it: "Lavoriamo a Roma.", en: "We work in Rome." },
          { it: "Mangiano la pizza.", en: "They eat pizza." },
        ],
      },
    ],
    dialogue: [
      {
        speaker: "Rosa",
        it: "Parli inglese?",
        en: "Do you speak English?",
      },
      {
        speaker: "Sam",
        it: "Sì, parlo inglese. Studio anche l'italiano.",
        en: "Yes, I speak English. I'm also studying Italian.",
      },
      {
        speaker: "Rosa",
        it: "Dove abiti?",
        en: "Where do you live?",
      },
      {
        speaker: "Sam",
        it: "Abito a Firenze.",
        en: "I live in Florence.",
      },
    ],
    exercises: [
      {
        id: "u4l1-1",
        type: "fill-blank",
        prompt: "io (parlare)",
        sentence: "Io ___ italiano.",
        answer: "parlo",
      },
      {
        id: "u4l1-2",
        type: "fill-blank",
        prompt: "tu (mangiare)",
        sentence: "Tu ___ la pasta.",
        answer: "mangi",
      },
      {
        id: "u4l1-3",
        type: "fill-blank",
        prompt: "noi (lavorare)",
        sentence: "Noi ___ molto.",
        answer: "lavoriamo",
      },
      {
        id: "u4l1-4",
        type: "multiple-choice",
        prompt: "loro (studiare):",
        options: ["studia", "studi", "studiano", "studiamo"],
        answer: 2,
      },
      {
        id: "u4l1-5",
        type: "match",
        prompt: "Match forms of parlare",
        pairs: [
          { left: "io", right: "parlo" },
          { left: "tu", right: "parli" },
          { left: "voi", right: "parlate" },
          { left: "loro", right: "parlano" },
        ],
      },
      {
        id: "u4l1-6",
        type: "multiple-choice",
        prompt: "«Abito a Firenze» means…",
        options: ["I work in Florence", "I live in Florence", "I study Florence", "I visit Florence"],
        answer: 1,
      },
      {
        id: "u4l1-7",
        type: "fill-blank",
        prompt: "lei (guardare)",
        sentence: "Lei ___ la TV.",
        answer: "guarda",
      },
      {
        id: "u4l1-8",
        type: "reorder",
        prompt: "Order the dialogue",
        lines: [
          "Parli inglese?",
          "Sì, parlo inglese. Studio anche l'italiano.",
          "Dove abiti?",
          "Abito a Firenze.",
        ],
      },
    ],
  },
  {
    id: "u4-l2",
    unitId: "unit-4",
    number: 14,
    title: "-ere & -ire Verbs",
    titleIt: "Verbi in -ere e -ire",
    summary: "Add regular -ere and -ire conjugations to your toolkit.",
    objectives: [
      "Conjugate prendere and scrivere",
      "Conjugate dormire and -isc- verbs like capire",
      "Contrast the three conjugations",
    ],
    vocabulary: [
      { it: "prendere", en: "to take / have (food/drink)" },
      { it: "scrivere", en: "to write" },
      { it: "leggere", en: "to read" },
      { it: "vendere", en: "to sell" },
      { it: "dormire", en: "to sleep" },
      { it: "aprire", en: "to open" },
      { it: "capire", en: "to understand" },
      { it: "finire", en: "to finish" },
      { it: "partire", en: "to leave / depart" },
    ],
    grammar: [
      {
        title: "-ere endings",
        explanation: "Drop -ere; add -o, -i, -e, -iamo, -ete, -ono.",
        examples: [
          { it: "Prendo un caffè.", en: "I'll have a coffee." },
          { it: "Scriviamo una email.", en: "We write an email." },
        ],
      },
      {
        title: "-ire and -isc-",
        explanation:
          "Some -ire verbs (dormire, aprire, partire) use -o, -i, -e, -iamo, -ite, -ono. Many others (capire, finire) insert -isc- in singular and loro forms: capisco, capisci, capisce, capiamo, capite, capiscono.",
        examples: [
          { it: "Dormo poco.", en: "I sleep little." },
          { it: "Capisco l'italiano.", en: "I understand Italian." },
        ],
      },
    ],
    dialogue: [
      {
        speaker: "Tina",
        it: "Capisci la lezione?",
        en: "Do you understand the lesson?",
      },
      {
        speaker: "Omar",
        it: "Sì, capisco bene. Leggo e scrivo ogni giorno.",
        en: "Yes, I understand well. I read and write every day.",
      },
      {
        speaker: "Tina",
        it: "A che ora parti?",
        en: "What time do you leave?",
      },
      {
        speaker: "Omar",
        it: "Parto alle otto.",
        en: "I leave at eight.",
      },
    ],
    exercises: [
      {
        id: "u4l2-1",
        type: "fill-blank",
        prompt: "io (prendere)",
        sentence: "___ un tè.",
        answer: "Prendo",
        accept: ["prendo"],
      },
      {
        id: "u4l2-2",
        type: "fill-blank",
        prompt: "noi (scrivere)",
        sentence: "Noi ___ una lettera.",
        answer: "scriviamo",
      },
      {
        id: "u4l2-3",
        type: "fill-blank",
        prompt: "io (capire)",
        sentence: "Io ___!",
        answer: "capisco",
      },
      {
        id: "u4l2-4",
        type: "multiple-choice",
        prompt: "loro (finire):",
        options: ["finiscono", "finano", "finiamo", "finite"],
        answer: 0,
      },
      {
        id: "u4l2-5",
        type: "match",
        prompt: "Match infinitives",
        pairs: [
          { left: "leggere", right: "to read" },
          { left: "dormire", right: "to sleep" },
          { left: "aprire", right: "to open" },
          { left: "vendere", right: "to sell" },
        ],
      },
      {
        id: "u4l2-6",
        type: "multiple-choice",
        prompt: "«Parto alle otto» means…",
        options: ["I sleep at 8", "I leave at 8", "I open at 8", "I write at 8"],
        answer: 1,
      },
      {
        id: "u4l2-7",
        type: "fill-blank",
        prompt: "tu (dormire)",
        sentence: "Tu ___ troppo!",
        answer: "dormi",
      },
      {
        id: "u4l2-8",
        type: "reorder",
        prompt: "Order the dialogue",
        lines: [
          "Capisci la lezione?",
          "Sì, capisco bene. Leggo e scrivo ogni giorno.",
          "A che ora parti?",
          "Parto alle otto.",
        ],
      },
    ],
  },
  {
    id: "u4-l3",
    unitId: "unit-4",
    number: 15,
    title: "Irregular Essentials",
    titleIt: "Verbi irregolari",
    summary: "Master avere, andare, fare, and volere — high-frequency irregulars.",
    objectives: [
      "Conjugate avere and use c'è / ci sono",
      "Use andare and fare in common phrases",
      "Express wants with volere",
    ],
    vocabulary: [
      { it: "avere", en: "to have" },
      { it: "andare", en: "to go" },
      { it: "fare", en: "to do / make" },
      { it: "volere", en: "to want" },
      { it: "ho fame", en: "I'm hungry" },
      { it: "ho sete", en: "I'm thirsty" },
      { it: "ho freddo / caldo", en: "I'm cold / hot" },
      { it: "vado", en: "I go" },
      { it: "faccio", en: "I do / make" },
      { it: "voglio", en: "I want" },
      { it: "c'è / ci sono", en: "there is / there are" },
    ],
    grammar: [
      {
        title: "Key irregular presents",
        explanation:
          "avere: ho, hai, ha, abbiamo, avete, hanno. andare: vado, vai, va, andiamo, andate, vanno. fare: faccio, fai, fa, facciamo, fate, fanno. volere: voglio, vuoi, vuole, vogliamo, volete, vogliono.",
        examples: [
          { it: "Ho una macchina.", en: "I have a car." },
          { it: "Vado a scuola.", en: "I go to school." },
          { it: "Che cosa fai?", en: "What are you doing?" },
          { it: "Voglio un gelato.", en: "I want an ice cream." },
        ],
      },
    ],
    dialogue: [
      {
        speaker: "Leo",
        it: "Hai fame?",
        en: "Are you hungry?",
      },
      {
        speaker: "Mia",
        it: "Sì, ho molta fame. Andiamo al ristorante?",
        en: "Yes, I'm very hungry. Shall we go to the restaurant?",
      },
      {
        speaker: "Leo",
        it: "Sì! Io voglio una pizza.",
        en: "Yes! I want a pizza.",
      },
      {
        speaker: "Mia",
        it: "Perfetto. C'è un posto qui vicino.",
        en: "Perfect. There's a place nearby.",
      },
    ],
    exercises: [
      {
        id: "u4l3-1",
        type: "fill-blank",
        prompt: "io (avere)",
        sentence: "___ fame.",
        answer: "Ho",
        accept: ["ho"],
      },
      {
        id: "u4l3-2",
        type: "fill-blank",
        prompt: "tu (andare)",
        sentence: "Dove ___?",
        answer: "vai",
      },
      {
        id: "u4l3-3",
        type: "fill-blank",
        prompt: "io (fare)",
        sentence: "Che cosa ___?",
        answer: "faccio",
      },
      {
        id: "u4l3-4",
        type: "fill-blank",
        prompt: "io (volere)",
        sentence: "___ un caffè.",
        answer: "Voglio",
        accept: ["voglio"],
      },
      {
        id: "u4l3-5",
        type: "match",
        prompt: "Match expressions",
        pairs: [
          { left: "ho sete", right: "I'm thirsty" },
          { left: "ho freddo", right: "I'm cold" },
          { left: "ci sono", right: "there are" },
          { left: "vado", right: "I go" },
        ],
      },
      {
        id: "u4l3-6",
        type: "multiple-choice",
        prompt: "loro (avere):",
        options: ["hanno", "avono", "hano", "avete"],
        answer: 0,
      },
      {
        id: "u4l3-7",
        type: "multiple-choice",
        prompt: "«C'è un posto» means…",
        options: ["There are places", "There is a place", "I want a place", "Go to a place"],
        answer: 1,
      },
      {
        id: "u4l3-8",
        type: "reorder",
        prompt: "Order the dialogue",
        lines: [
          "Hai fame?",
          "Sì, ho molta fame. Andiamo al ristorante?",
          "Sì! Io voglio una pizza.",
          "Perfetto. C'è un posto qui vicino.",
        ],
      },
    ],
  },
  {
    id: "u4-l4",
    unitId: "unit-4",
    number: 16,
    title: "Daily Routines",
    titleIt: "La giornata",
    summary: "Describe a typical day with frequency adverbs and reflexive verbs.",
    objectives: [
      "Talk about morning-to-night routines",
      "Use sempre, spesso, a volte, mai",
      "Use basic reflexives: mi alzo, mi lavo",
    ],
    vocabulary: [
      { it: "mi alzo", en: "I get up" },
      { it: "mi lavo", en: "I wash (myself)" },
      { it: "mi vesto", en: "I get dressed" },
      { it: "faccio colazione", en: "I have breakfast" },
      { it: "vado a lavoro / a scuola", en: "I go to work / school" },
      { it: "riento", en: "I return home" },
      { it: "ceno", en: "I have dinner" },
      { it: "vado a letto", en: "I go to bed" },
      { it: "sempre", en: "always" },
      { it: "spesso", en: "often" },
      { it: "a volte", en: "sometimes" },
      { it: "mai", en: "never" },
    ],
    grammar: [
      {
        title: "Reflexive present",
        explanation:
          "Reflexive verbs use mi, ti, si, ci, vi, si before the conjugated verb: mi alzo, ti alzi, si alza… Place frequency adverbs after the verb or at the start: Non vado mai a letto tardi.",
        examples: [
          { it: "Mi alzo alle sette.", en: "I get up at seven." },
          { it: "A volte ceno fuori.", en: "Sometimes I eat dinner out." },
        ],
      },
    ],
    dialogue: [
      {
        speaker: "Giada",
        it: "A che ora ti alzi?",
        en: "What time do you get up?",
      },
      {
        speaker: "Nico",
        it: "Mi alzo alle sette. Poi faccio colazione e vado a lavoro.",
        en: "I get up at seven. Then I have breakfast and go to work.",
      },
      {
        speaker: "Giada",
        it: "Lavori sempre fino a tardi?",
        en: "Do you always work until late?",
      },
      {
        speaker: "Nico",
        it: "No, a volte riento presto.",
        en: "No, sometimes I get home early.",
      },
    ],
    exercises: [
      {
        id: "u4l4-1",
        type: "fill-blank",
        prompt: "I get up",
        sentence: "___ alzo alle otto.",
        answer: "Mi",
        accept: ["mi"],
      },
      {
        id: "u4l4-2",
        type: "match",
        prompt: "Match routine phrases",
        pairs: [
          { left: "faccio colazione", right: "I have breakfast" },
          { left: "vado a letto", right: "I go to bed" },
          { left: "spesso", right: "often" },
          { left: "mai", right: "never" },
        ],
      },
      {
        id: "u4l4-3",
        type: "multiple-choice",
        prompt: "«A volte» means…",
        options: ["always", "never", "sometimes", "already"],
        answer: 2,
      },
      {
        id: "u4l4-4",
        type: "fill-blank",
        prompt: "you get up (informal)",
        sentence: "A che ora ti ___?",
        answer: "alzi",
      },
      {
        id: "u4l4-5",
        type: "multiple-choice",
        prompt: "«Mi lavo» means…",
        options: ["I wash myself", "I leave", "I work", "I sleep"],
        answer: 0,
      },
      {
        id: "u4l4-6",
        type: "fill-blank",
        prompt: "never (with negation)",
        sentence: "Non vado ___ in centro.",
        answer: "mai",
      },
      {
        id: "u4l4-7",
        type: "multiple-choice",
        prompt: "«Riento presto» ≈",
        options: ["I leave early", "I get home early", "I wake early", "I eat early"],
        answer: 1,
      },
      {
        id: "u4l4-8",
        type: "reorder",
        prompt: "Order the dialogue",
        lines: [
          "A che ora ti alzi?",
          "Mi alzo alle sette. Poi faccio colazione e vado a lavoro.",
          "Lavori sempre fino a tardi?",
          "No, a volte riento presto.",
        ],
      },
    ],
  },
];
