import type { Lesson } from "@/lib/types";

export const unit3Lessons: Lesson[] = [
  {
    id: "u3-l1",
    unitId: "unit-3",
    number: 9,
    title: "Articles",
    titleIt: "Gli articoli",
    summary: "Definite and indefinite articles with masculine and feminine nouns.",
    objectives: [
      "Use il, lo, l', la, i, gli, le",
      "Use un, uno, una, un'",
      "Choose the article from the noun's start sound",
    ],
    vocabulary: [
      { it: "il libro", en: "the book" },
      { it: "lo studente", en: "the student (m)" },
      { it: "l'amico", en: "the friend (m)" },
      { it: "la casa", en: "the house" },
      { it: "i libri", en: "the books" },
      { it: "gli studenti", en: "the students (m)" },
      { it: "le case", en: "the houses" },
      { it: "un amico", en: "a friend (m)" },
      { it: "una amica", en: "a friend (f)", note: "often un'amica" },
      { it: "uno zaino", en: "a backpack" },
    ],
    grammar: [
      {
        title: "Definite articles",
        explanation:
          "Masculine: il / i before most consonants; lo / gli before s+consonant, z, ps, gn, x, y; l' / gli before vowels. Feminine: la / le; l' before vowels.",
        examples: [
          { it: "il ragazzo / i ragazzi", en: "the boy / the boys" },
          { it: "lo zio / gli zii", en: "the uncle / the uncles" },
          { it: "l'università / le università", en: "the university / universities" },
        ],
      },
      {
        title: "Indefinite articles",
        explanation:
          "un (most m.), uno (same cases as lo), una (f.), un' (f. before vowel).",
        examples: [
          { it: "un libro", en: "a book" },
          { it: "uno studente", en: "a student" },
          { it: "un'ora", en: "an hour" },
        ],
      },
    ],
    dialogue: [
      {
        speaker: "Marta",
        it: "Hai un libro?",
        en: "Do you have a book?",
      },
      {
        speaker: "Luca",
        it: "Sì, ho il libro di italiano.",
        en: "Yes, I have the Italian book.",
      },
      {
        speaker: "Marta",
        it: "Perfetto. C'è anche uno zaino?",
        en: "Perfect. Is there also a backpack?",
      },
      {
        speaker: "Luca",
        it: "Sì, lo zaino è qui.",
        en: "Yes, the backpack is here.",
      },
    ],
    exercises: [
      {
        id: "u3l1-1",
        type: "multiple-choice",
        prompt: "Article for «libro» (the):",
        options: ["la", "il", "lo", "le"],
        answer: 1,
      },
      {
        id: "u3l1-2",
        type: "multiple-choice",
        prompt: "Article for «studente» (the):",
        options: ["il", "lo", "la", "le"],
        answer: 1,
      },
      {
        id: "u3l1-3",
        type: "fill-blank",
        prompt: "___ amico (the friend, m.)",
        sentence: "___ amico",
        answer: "l'",
        accept: ["l", "L'"],
      },
      {
        id: "u3l1-4",
        type: "fill-blank",
        prompt: "a backpack",
        sentence: "___ zaino",
        answer: "uno",
      },
      {
        id: "u3l1-5",
        type: "match",
        prompt: "Match article + noun",
        pairs: [
          { left: "il", right: "pane" },
          { left: "la", right: "casa" },
          { left: "gli", right: "studenti" },
          { left: "le", right: "case" },
        ],
      },
      {
        id: "u3l1-6",
        type: "multiple-choice",
        prompt: "Plural of «il libro»:",
        options: ["i libri", "gli libri", "le libri", "lo libri"],
        answer: 0,
      },
      {
        id: "u3l1-7",
        type: "fill-blank",
        prompt: "an hour (f. before vowel)",
        sentence: "___ ora",
        answer: "un'",
        accept: ["un", "una"],
      },
      {
        id: "u3l1-8",
        type: "reorder",
        prompt: "Order the dialogue",
        lines: [
          "Hai un libro?",
          "Sì, ho il libro di italiano.",
          "Perfetto. C'è anche uno zaino?",
          "Sì, lo zaino è qui.",
        ],
      },
    ],
  },
  {
    id: "u3-l2",
    unitId: "unit-3",
    number: 10,
    title: "Gender & Number",
    titleIt: "Genere e numero",
    summary: "Make nouns masculine/feminine and singular/plural.",
    objectives: [
      "Recognize -o / -a / -e noun patterns",
      "Form regular plurals",
      "Spot common irregular plurals",
    ],
    vocabulary: [
      { it: "ragazzo / ragazza", en: "boy / girl" },
      { it: "amico / amica", en: "friend (m/f)" },
      { it: "professore / professoressa", en: "professor (m/f)" },
      { it: "città", en: "city", gender: "f" },
      { it: "problema", en: "problem", gender: "m", note: "ends in -a but masculine" },
      { it: "mano", en: "hand", gender: "f", note: "ends in -o but feminine" },
      { it: "uovo → uova", en: "egg → eggs" },
      { it: "uomo → uomini", en: "man → men" },
    ],
    grammar: [
      {
        title: "Regular plurals",
        explanation:
          "Most -o nouns → -i (masculine). Most -a nouns → -e (feminine). Many -e nouns → -i for both genders.",
        examples: [
          { it: "libro → libri", en: "book → books" },
          { it: "casa → case", en: "house → houses" },
          { it: "studente → studenti", en: "student → students" },
        ],
      },
    ],
    dialogue: [
      {
        speaker: "Nora",
        it: "Quanti amici hai?",
        en: "How many friends do you have?",
      },
      {
        speaker: "Pietro",
        it: "Ho due amici e tre amiche.",
        en: "I have two male friends and three female friends.",
      },
      {
        speaker: "Nora",
        it: "Che bella città!",
        en: "What a beautiful city!",
      },
    ],
    exercises: [
      {
        id: "u3l2-1",
        type: "fill-blank",
        prompt: "Plural of libro",
        sentence: "libro → ___",
        answer: "libri",
      },
      {
        id: "u3l2-2",
        type: "fill-blank",
        prompt: "Plural of casa",
        sentence: "casa → ___",
        answer: "case",
      },
      {
        id: "u3l2-3",
        type: "multiple-choice",
        prompt: "«Problema» is…",
        options: ["feminine", "masculine", "plural", "a verb"],
        answer: 1,
      },
      {
        id: "u3l2-4",
        type: "multiple-choice",
        prompt: "«Mano» is…",
        options: ["masculine", "feminine", "neuter", "plural"],
        answer: 1,
      },
      {
        id: "u3l2-5",
        type: "match",
        prompt: "Match singular → plural",
        pairs: [
          { left: "ragazzo", right: "ragazzi" },
          { left: "ragazza", right: "ragazze" },
          { left: "uomo", right: "uomini" },
          { left: "città", right: "città" },
        ],
      },
      {
        id: "u3l2-6",
        type: "fill-blank",
        prompt: "Feminine of amico",
        sentence: "amico → ___",
        answer: "amica",
      },
      {
        id: "u3l2-7",
        type: "multiple-choice",
        prompt: "Plural of studente:",
        options: ["studente", "studenti", "studentes", "studenta"],
        answer: 1,
      },
      {
        id: "u3l2-8",
        type: "reorder",
        prompt: "Order the dialogue",
        lines: [
          "Quanti amici hai?",
          "Ho due amici e tre amiche.",
          "Che bella città!",
        ],
      },
    ],
  },
  {
    id: "u3-l3",
    unitId: "unit-3",
    number: 11,
    title: "Adjectives",
    titleIt: "Gli aggettivi",
    summary: "Make adjectives agree and place them naturally in sentences.",
    objectives: [
      "Agree adjectives in gender and number",
      "Use common -o/-a and -e adjectives",
      "Describe people and things simply",
    ],
    vocabulary: [
      { it: "bello / bella", en: "beautiful / nice" },
      { it: "buono / buona", en: "good" },
      { it: "nuovo / nuova", en: "new" },
      { it: "vecchio / vecchia", en: "old" },
      { it: "grande", en: "big / great" },
      { it: "piccolo / piccola", en: "small" },
      { it: "interessante", en: "interesting" },
      { it: "difficile", en: "difficult" },
      { it: "facile", en: "easy" },
      { it: "simpatico / simpatica", en: "nice / likeable" },
    ],
    grammar: [
      {
        title: "Agreement",
        explanation:
          "Adjectives ending in -o change to -a/-i/-e. Adjectives ending in -e become -i in the plural for both genders. They usually follow the noun, though bello/buono/grande often come before.",
        examples: [
          { it: "una casa nuova", en: "a new house" },
          { it: "libri interessanti", en: "interesting books" },
          { it: "un bel giorno", en: "a nice day" },
        ],
      },
    ],
    dialogue: [
      {
        speaker: "Chiara",
        it: "Com'è il corso?",
        en: "How's the course?",
      },
      {
        speaker: "Davide",
        it: "È interessante, ma un po' difficile.",
        en: "It's interesting, but a bit difficult.",
      },
      {
        speaker: "Chiara",
        it: "La professoressa è simpatica?",
        en: "Is the professor nice?",
      },
      {
        speaker: "Davide",
        it: "Sì, è molto simpatica!",
        en: "Yes, she's very nice!",
      },
    ],
    exercises: [
      {
        id: "u3l3-1",
        type: "fill-blank",
        prompt: "Agree: una pizza ___ (buono)",
        sentence: "una pizza ___",
        answer: "buona",
      },
      {
        id: "u3l3-2",
        type: "fill-blank",
        prompt: "Agree: i libri ___ (nuovo)",
        sentence: "i libri ___",
        answer: "nuovi",
      },
      {
        id: "u3l3-3",
        type: "multiple-choice",
        prompt: "Plural of «interessante»:",
        options: ["interessanta", "interessanti", "interessante", "interessanti e"],
        answer: 1,
      },
      {
        id: "u3l3-4",
        type: "match",
        prompt: "Match adjectives",
        pairs: [
          { left: "piccolo", right: "small" },
          { left: "difficile", right: "difficult" },
          { left: "facile", right: "easy" },
          { left: "vecchio", right: "old" },
        ],
      },
      {
        id: "u3l3-5",
        type: "multiple-choice",
        prompt: "«Simpatica» agrees with…",
        options: ["il ragazzo", "la ragazza", "i ragazzi", "gli uomini"],
        answer: 1,
      },
      {
        id: "u3l3-6",
        type: "fill-blank",
        prompt: "a big city",
        sentence: "una città ___",
        answer: "grande",
      },
      {
        id: "u3l3-7",
        type: "multiple-choice",
        prompt: "«È un po' difficile» means…",
        options: ["It's very easy", "It's a bit difficult", "It's new", "It's beautiful"],
        answer: 1,
      },
      {
        id: "u3l3-8",
        type: "reorder",
        prompt: "Order the dialogue",
        lines: [
          "Com'è il corso?",
          "È interessante, ma un po' difficile.",
          "La professoressa è simpatica?",
          "Sì, è molto simpatica!",
        ],
      },
    ],
  },
  {
    id: "u3-l4",
    unitId: "unit-3",
    number: 12,
    title: "Family",
    titleIt: "La famiglia",
    summary: "Talk about family members and possessive adjectives.",
    objectives: [
      "Name close family members",
      "Use mio/mia/tuo/tua with family",
      "Describe family simply with avere and essere",
    ],
    vocabulary: [
      { it: "madre / mamma", en: "mother / mom" },
      { it: "padre / papà", en: "father / dad" },
      { it: "fratello", en: "brother", gender: "m" },
      { it: "sorella", en: "sister", gender: "f" },
      { it: "figlio / figlia", en: "son / daughter" },
      { it: "nonno / nonna", en: "grandfather / grandmother" },
      { it: "marito / moglie", en: "husband / wife" },
      { it: "mio / mia", en: "my (m/f)" },
      { it: "tuo / tua", en: "your (m/f informal)" },
      { it: "famiglia", en: "family", gender: "f" },
    ],
    grammar: [
      {
        title: "Possessives with family",
        explanation:
          "With singular unmodified family nouns, Italian often drops the definite article: mio fratello, mia madre. Use the article with plural or modified nouns: i miei fratelli, la mia cara sorella.",
        examples: [
          { it: "Mia sorella è alta.", en: "My sister is tall." },
          { it: "I miei genitori sono italiani.", en: "My parents are Italian." },
        ],
      },
    ],
    dialogue: [
      {
        speaker: "Alice",
        it: "Hai fratelli?",
        en: "Do you have siblings?",
      },
      {
        speaker: "Marco",
        it: "Sì, ho un fratello e una sorella.",
        en: "Yes, I have one brother and one sister.",
      },
      {
        speaker: "Alice",
        it: "Come si chiama tuo fratello?",
        en: "What's your brother's name?",
      },
      {
        speaker: "Marco",
        it: "Si chiama Luca. E tua madre?",
        en: "His name is Luca. And your mother?",
      },
    ],
    exercises: [
      {
        id: "u3l4-1",
        type: "match",
        prompt: "Match family words",
        pairs: [
          { left: "fratello", right: "brother" },
          { left: "sorella", right: "sister" },
          { left: "nonna", right: "grandmother" },
          { left: "padre", right: "father" },
        ],
      },
      {
        id: "u3l4-2",
        type: "fill-blank",
        prompt: "my sister",
        sentence: "___ sorella",
        answer: "mia",
      },
      {
        id: "u3l4-3",
        type: "fill-blank",
        prompt: "your brother (informal)",
        sentence: "___ fratello",
        answer: "tuo",
      },
      {
        id: "u3l4-4",
        type: "multiple-choice",
        prompt: "«Moglie» means…",
        options: ["husband", "wife", "daughter", "aunt"],
        answer: 1,
      },
      {
        id: "u3l4-5",
        type: "multiple-choice",
        prompt: "«Hai fratelli?» asks about…",
        options: ["pets", "siblings", "jobs", "cities"],
        answer: 1,
      },
      {
        id: "u3l4-6",
        type: "fill-blank",
        prompt: "son",
        sentence: "figlio = ___",
        answer: "son",
      },
      {
        id: "u3l4-7",
        type: "multiple-choice",
        prompt: "Correct: «___ genitori»",
        options: ["mio", "mia", "i miei", "le mie"],
        answer: 2,
      },
      {
        id: "u3l4-8",
        type: "reorder",
        prompt: "Order the dialogue",
        lines: [
          "Hai fratelli?",
          "Sì, ho un fratello e una sorella.",
          "Come si chiama tuo fratello?",
          "Si chiama Luca. E tua madre?",
        ],
      },
    ],
  },
];
