import type { Lesson } from "@/lib/types";

export const unit5Lessons: Lesson[] = [
  {
    id: "u5-l1",
    unitId: "unit-5",
    number: 17,
    title: "Places in Town",
    titleIt: "In città",
    summary: "Name common places and say where you are going.",
    objectives: [
      "Name shops and public places",
      "Use a / in with place names",
      "Ask dov'è…?",
    ],
    vocabulary: [
      { it: "città", en: "city", gender: "f" },
      { it: "strada", en: "street", gender: "f" },
      { it: "piazza", en: "square", gender: "f" },
      { it: "stazione", en: "station", gender: "f" },
      { it: "banco / banca", en: "counter / bank" },
      { it: "farmacia", en: "pharmacy", gender: "f" },
      { it: "supermercato", en: "supermarket", gender: "m" },
      { it: "museo", en: "museum", gender: "m" },
      { it: "ristorante", en: "restaurant", gender: "m" },
      { it: "albergo / hotel", en: "hotel", gender: "m" },
      { it: "dov'è…?", en: "where is…?" },
    ],
    grammar: [
      {
        title: "A vs in",
        explanation:
          "Use a with cities and many point destinations (a Roma, a scuola, al museo). Use in with countries, regions, and some enclosed places (in Italia, in banca, in centro).",
        examples: [
          { it: "Vado a Milano.", en: "I'm going to Milan." },
          { it: "Lavoro in banca.", en: "I work at a bank." },
          { it: "Dov'è la stazione?", en: "Where is the station?" },
        ],
      },
    ],
    dialogue: [
      {
        speaker: "Turista",
        it: "Scusi, dov'è il museo?",
        en: "Excuse me, where is the museum?",
      },
      {
        speaker: "Locale",
        it: "Il museo è in piazza Maggiore.",
        en: "The museum is in Piazza Maggiore.",
      },
      {
        speaker: "Turista",
        it: "E la farmacia?",
        en: "And the pharmacy?",
      },
      {
        speaker: "Locale",
        it: "È qui vicino, in via Roma.",
        en: "It's nearby, on Via Roma.",
      },
    ],
    exercises: [
      {
        id: "u5l1-1",
        type: "match",
        prompt: "Match places",
        pairs: [
          { left: "stazione", right: "station" },
          { left: "farmacia", right: "pharmacy" },
          { left: "museo", right: "museum" },
          { left: "piazza", right: "square" },
        ],
      },
      {
        id: "u5l1-2",
        type: "fill-blank",
        prompt: "Where is…?",
        sentence: "___ il ristorante?",
        answer: "Dov'è",
        accept: ["Dove è", "dov'è", "dove è"],
      },
      {
        id: "u5l1-3",
        type: "multiple-choice",
        prompt: "«Vado ___ Roma»",
        options: ["in", "a", "di", "su"],
        answer: 1,
      },
      {
        id: "u5l1-4",
        type: "multiple-choice",
        prompt: "«Lavoro ___ banca»",
        options: ["a", "in", "di", "per"],
        answer: 1,
      },
      {
        id: "u5l1-5",
        type: "fill-blank",
        prompt: "supermarket",
        sentence: "supermercato = ___",
        answer: "supermarket",
      },
      {
        id: "u5l1-6",
        type: "multiple-choice",
        prompt: "Hotel in Italian can be…",
        options: ["farmacia", "albergo", "strada", "piazza"],
        answer: 1,
      },
      {
        id: "u5l1-7",
        type: "fill-blank",
        prompt: "nearby",
        sentence: "È qui ___.",
        answer: "vicino",
      },
      {
        id: "u5l1-8",
        type: "reorder",
        prompt: "Order the dialogue",
        lines: [
          "Scusi, dov'è il museo?",
          "Il museo è in piazza Maggiore.",
          "E la farmacia?",
          "È qui vicino, in via Roma.",
        ],
      },
    ],
  },
  {
    id: "u5-l2",
    unitId: "unit-5",
    number: 18,
    title: "Prepositions",
    titleIt: "Le preposizioni",
    summary: "Use di, a, da, in, con, su, per and common articulated forms.",
    objectives: [
      "Use core simple prepositions",
      "Form del, al, dal, nel, sul",
      "Describe location with su / sotto / vicino a",
    ],
    vocabulary: [
      { it: "di", en: "of / from" },
      { it: "a", en: "to / at" },
      { it: "da", en: "from / at (someone's)" },
      { it: "in", en: "in" },
      { it: "con", en: "with" },
      { it: "su", en: "on" },
      { it: "per", en: "for / through" },
      { it: "del / della", en: "of the" },
      { it: "al / alla", en: "to the / at the" },
      { it: "nel / nella", en: "in the" },
      { it: "vicino a", en: "near" },
      { it: "lontano da", en: "far from" },
    ],
    grammar: [
      {
        title: "Articulated prepositions",
        explanation:
          "di/a/da/in/su combine with the definite article: di + il = del, a + la = alla, in + lo = nello, su + i = sui, etc.",
        examples: [
          { it: "Il libro del professore", en: "The teacher's book" },
          { it: "Vado al cinema", en: "I'm going to the cinema" },
          { it: "Nella borsa c'è un libro", en: "In the bag there's a book" },
        ],
      },
    ],
    dialogue: [
      {
        speaker: "Eva",
        it: "Il caffè è sul tavolo.",
        en: "The coffee is on the table.",
      },
      {
        speaker: "Piero",
        it: "E le chiavi?",
        en: "And the keys?",
      },
      {
        speaker: "Eva",
        it: "Sono nella borsa, con il portafoglio.",
        en: "They're in the bag, with the wallet.",
      },
      {
        speaker: "Piero",
        it: "Perfetto. Andiamo da Maria?",
        en: "Perfect. Shall we go to Maria's?",
      },
    ],
    exercises: [
      {
        id: "u5l2-1",
        type: "multiple-choice",
        prompt: "di + il =",
        options: ["dal", "del", "nel", "sul"],
        answer: 1,
      },
      {
        id: "u5l2-2",
        type: "multiple-choice",
        prompt: "a + la =",
        options: ["alla", "della", "nella", "sulla"],
        answer: 0,
      },
      {
        id: "u5l2-3",
        type: "fill-blank",
        prompt: "on the table",
        sentence: "___ tavolo",
        answer: "sul",
      },
      {
        id: "u5l2-4",
        type: "fill-blank",
        prompt: "in the bag (f.)",
        sentence: "___ borsa",
        answer: "nella",
      },
      {
        id: "u5l2-5",
        type: "match",
        prompt: "Match prepositions",
        pairs: [
          { left: "con", right: "with" },
          { left: "per", right: "for" },
          { left: "vicino a", right: "near" },
          { left: "lontano da", right: "far from" },
        ],
      },
      {
        id: "u5l2-6",
        type: "multiple-choice",
        prompt: "«Andiamo da Maria» means…",
        options: ["We leave Maria", "We're going to Maria's", "We're with Maria", "We're far from Maria"],
        answer: 1,
      },
      {
        id: "u5l2-7",
        type: "fill-blank",
        prompt: "with the wallet",
        sentence: "___ il portafoglio",
        answer: "con",
      },
      {
        id: "u5l2-8",
        type: "reorder",
        prompt: "Order the dialogue",
        lines: [
          "Il caffè è sul tavolo.",
          "E le chiavi?",
          "Sono nella borsa, con il portafoglio.",
          "Perfetto. Andiamo da Maria?",
        ],
      },
    ],
  },
  {
    id: "u5-l3",
    unitId: "unit-5",
    number: 19,
    title: "Directions",
    titleIt: "Le indicazioni",
    summary: "Ask for and give simple directions around town.",
    objectives: [
      "Ask how to get somewhere",
      "Understand gira a destra / sinistra, dritto",
      "Use quanti metri / quanto tempo",
    ],
    vocabulary: [
      { it: "a destra", en: "to the right" },
      { it: "a sinistra", en: "to the left" },
      { it: "dritto / sempre dritto", en: "straight ahead" },
      { it: "gira / giri", en: "turn (imperative forms)" },
      { it: "incrocio", en: "intersection", gender: "m" },
      { it: "semaforo", en: "traffic light", gender: "m" },
      { it: "angolo", en: "corner", gender: "m" },
      { it: "vicino", en: "near / nearby" },
      { it: "quanto dista?", en: "how far is it?" },
      { it: "a piedi", en: "on foot" },
    ],
    grammar: [
      {
        title: "Giving directions",
        explanation:
          "Use informal gira / vai or formal giri / vada. Combine with prepositional phrases: gira a destra al semaforo, vai sempre dritto.",
        examples: [
          { it: "Vai sempre dritto.", en: "Go straight ahead." },
          { it: "Gira a sinistra all'incrocio.", en: "Turn left at the intersection." },
        ],
      },
    ],
    dialogue: [
      {
        speaker: "Turista",
        it: "Scusi, per la stazione?",
        en: "Excuse me, for the station?",
      },
      {
        speaker: "Locale",
        it: "Vada sempre dritto, poi giri a destra al semaforo.",
        en: "Go straight, then turn right at the light.",
      },
      {
        speaker: "Turista",
        it: "È lontana?",
        en: "Is it far?",
      },
      {
        speaker: "Locale",
        it: "No, cinque minuti a piedi.",
        en: "No, five minutes on foot.",
      },
    ],
    exercises: [
      {
        id: "u5l3-1",
        type: "match",
        prompt: "Match direction words",
        pairs: [
          { left: "a destra", right: "to the right" },
          { left: "a sinistra", right: "to the left" },
          { left: "dritto", right: "straight" },
          { left: "a piedi", right: "on foot" },
        ],
      },
      {
        id: "u5l3-2",
        type: "multiple-choice",
        prompt: "Traffic light:",
        options: ["incrocio", "semaforo", "angolo", "strada"],
        answer: 1,
      },
      {
        id: "u5l3-3",
        type: "fill-blank",
        prompt: "Turn right",
        sentence: "Gira a ___.",
        answer: "destra",
      },
      {
        id: "u5l3-4",
        type: "fill-blank",
        prompt: "Go straight",
        sentence: "Vai sempre ___.",
        answer: "dritto",
      },
      {
        id: "u5l3-5",
        type: "multiple-choice",
        prompt: "«Cinque minuti a piedi» means…",
        options: ["5 minutes by car", "5 minutes on foot", "5 meters away", "turn in 5 minutes"],
        answer: 1,
      },
      {
        id: "u5l3-6",
        type: "multiple-choice",
        prompt: "Ask how far:",
        options: ["quanto costa?", "quanto dista?", "che ora è?", "come stai?"],
        answer: 1,
      },
      {
        id: "u5l3-7",
        type: "fill-blank",
        prompt: "intersection",
        sentence: "all'___",
        answer: "incrocio",
      },
      {
        id: "u5l3-8",
        type: "reorder",
        prompt: "Order the dialogue",
        lines: [
          "Scusi, per la stazione?",
          "Vada sempre dritto, poi giri a destra al semaforo.",
          "È lontana?",
          "No, cinque minuti a piedi.",
        ],
      },
    ],
  },
  {
    id: "u5-l4",
    unitId: "unit-5",
    number: 20,
    title: "Shopping & Ordering",
    titleIt: "Shopping e al bar",
    summary: "Buy things and order food and drinks with confidence.",
    objectives: [
      "Ask prices with quanto costa?",
      "Use vorrei and prendo",
      "Handle sizes, quantities, and payment basics",
    ],
    vocabulary: [
      { it: "quanto costa?", en: "how much does it cost?" },
      { it: "vorrei…", en: "I would like…" },
      { it: "prendo…", en: "I'll have…" },
      { it: "il conto", en: "the bill", gender: "m" },
      { it: "carta / contanti", en: "card / cash" },
      { it: "taglia", en: "size", gender: "f" },
      { it: "troppo caro", en: "too expensive" },
      { it: "sconto", en: "discount", gender: "m" },
      { it: "etto / chilo", en: "100g / kilo" },
      { it: "altro?", en: "anything else?" },
    ],
    grammar: [
      {
        title: "Polite ordering",
        explanation:
          "Vorrei (from volere) is softer than voglio for requests. At a bar, prendo + item is natural. Ask for the bill with il conto, per favore.",
        examples: [
          { it: "Vorrei un cappuccino.", en: "I'd like a cappuccino." },
          { it: "Prendo un panino.", en: "I'll have a sandwich." },
          { it: "Il conto, per favore.", en: "The bill, please." },
        ],
      },
    ],
    dialogue: [
      {
        speaker: "Cliente",
        it: "Buongiorno, vorrei un etto di prosciutto.",
        en: "Good morning, I'd like 100g of ham.",
      },
      {
        speaker: "Negoziante",
        it: "Ecco a Lei. Altro?",
        en: "Here you are. Anything else?",
      },
      {
        speaker: "Cliente",
        it: "No, grazie. Quanto costa?",
        en: "No, thanks. How much is it?",
      },
      {
        speaker: "Negoziante",
        it: "Quattro euro. Contanti o carta?",
        en: "Four euros. Cash or card?",
      },
    ],
    exercises: [
      {
        id: "u5l4-1",
        type: "fill-blank",
        prompt: "How much does it cost?",
        sentence: "Quanto ___?",
        answer: "costa",
      },
      {
        id: "u5l4-2",
        type: "fill-blank",
        prompt: "I would like…",
        sentence: "___ un tè, per favore.",
        answer: "Vorrei",
        accept: ["vorrei"],
      },
      {
        id: "u5l4-3",
        type: "match",
        prompt: "Match shopping phrases",
        pairs: [
          { left: "il conto", right: "the bill" },
          { left: "contanti", right: "cash" },
          { left: "taglia", right: "size" },
          { left: "sconto", right: "discount" },
        ],
      },
      {
        id: "u5l4-4",
        type: "multiple-choice",
        prompt: "«Troppo caro» means…",
        options: ["too big", "too expensive", "on sale", "sold out"],
        answer: 1,
      },
      {
        id: "u5l4-5",
        type: "multiple-choice",
        prompt: "«Altro?» in a shop ≈",
        options: ["Hello?", "Anything else?", "How much?", "Receipt?"],
        answer: 1,
      },
      {
        id: "u5l4-6",
        type: "fill-blank",
        prompt: "the bill please",
        sentence: "Il ___, per favore.",
        answer: "conto",
      },
      {
        id: "u5l4-7",
        type: "multiple-choice",
        prompt: "An «etto» is about…",
        options: ["10g", "100g", "1kg", "1 liter"],
        answer: 1,
      },
      {
        id: "u5l4-8",
        type: "reorder",
        prompt: "Order the shopping dialogue",
        lines: [
          "Buongiorno, vorrei un etto di prosciutto.",
          "Ecco a Lei. Altro?",
          "No, grazie. Quanto costa?",
          "Quattro euro. Contanti o carta?",
        ],
      },
    ],
  },
];
