import type { Lesson } from "@/lib/types";

export const unit2Lessons: Lesson[] = [
  {
    id: "u2-l1",
    unitId: "unit-2",
    number: 5,
    title: "Numbers 0–100",
    titleIt: "I numeri",
    summary: "Count from zero to one hundred and use numbers in simple contexts.",
    objectives: [
      "Count 0–20 fluently",
      "Form tens and compounds to 100",
      "Ask quanto / quanti?",
    ],
    vocabulary: [
      { it: "zero", en: "zero" },
      { it: "uno / una", en: "one" },
      { it: "due", en: "two" },
      { it: "tre", en: "three" },
      { it: "quattro", en: "four" },
      { it: "cinque", en: "five" },
      { it: "sei", en: "six" },
      { it: "sette", en: "seven" },
      { it: "otto", en: "eight" },
      { it: "nove", en: "nine" },
      { it: "dieci", en: "ten" },
      { it: "undici", en: "eleven" },
      { it: "dodici", en: "twelve" },
      { it: "venti", en: "twenty" },
      { it: "trenta", en: "thirty" },
      { it: "cento", en: "one hundred" },
      { it: "quanto / quanti?", en: "how much / how many?" },
    ],
    grammar: [
      {
        title: "Building teens and tens",
        explanation:
          "11–16 are unique forms (undici…sedici). 17–19 use -dici. From 20 up, combine ten + digit; drop the final vowel of the ten before uno/otto: ventuno, ventotto.",
        examples: [
          { it: "sedici", en: "sixteen" },
          { it: "ventuno", en: "twenty-one" },
          { it: "trentotto", en: "thirty-eight" },
        ],
      },
    ],
    dialogue: [
      {
        speaker: "Cassiere",
        it: "Sono cinque euro.",
        en: "That's five euros.",
      },
      {
        speaker: "Cliente",
        it: "Ecco dieci euro.",
        en: "Here's ten euros.",
      },
      {
        speaker: "Cassiere",
        it: "Ecco cinque euro di resto. Grazie!",
        en: "Here's five euros change. Thank you!",
      },
    ],
    exercises: [
      {
        id: "u2l1-1",
        type: "match",
        prompt: "Match numbers",
        pairs: [
          { left: "tre", right: "3" },
          { left: "sette", right: "7" },
          { left: "dieci", right: "10" },
          { left: "dodici", right: "12" },
        ],
      },
      {
        id: "u2l1-2",
        type: "multiple-choice",
        prompt: "«Undici» is…",
        options: ["8", "9", "11", "12"],
        answer: 2,
      },
      {
        id: "u2l1-3",
        type: "fill-blank",
        prompt: "Write 20 in Italian",
        sentence: "20 = ___",
        answer: "venti",
      },
      {
        id: "u2l1-4",
        type: "fill-blank",
        prompt: "Write 21 in Italian",
        sentence: "21 = ___",
        answer: "ventuno",
      },
      {
        id: "u2l1-5",
        type: "multiple-choice",
        prompt: "«Cento» means…",
        options: ["10", "20", "50", "100"],
        answer: 3,
      },
      {
        id: "u2l1-6",
        type: "multiple-choice",
        prompt: "How do you ask «how many?»",
        options: ["quando?", "quanti?", "dove?", "chi?"],
        answer: 1,
      },
      {
        id: "u2l1-7",
        type: "fill-blank",
        prompt: "Complete: five euros",
        sentence: "___ euro",
        answer: "cinque",
      },
      {
        id: "u2l1-8",
        type: "reorder",
        prompt: "Order the café exchange",
        lines: [
          "Sono cinque euro.",
          "Ecco dieci euro.",
          "Ecco cinque euro di resto. Grazie!",
        ],
      },
    ],
  },
  {
    id: "u2-l2",
    unitId: "unit-2",
    number: 6,
    title: "Time of Day",
    titleIt: "Che ora è?",
    summary: "Tell the time and talk about morning, afternoon, and evening.",
    objectives: [
      "Ask and tell the time",
      "Use di mattina / di pomeriggio / di sera",
      "Say a che ora…?",
    ],
    vocabulary: [
      { it: "che ora è?", en: "what time is it?" },
      { it: "è l'una", en: "it's one o'clock" },
      { it: "sono le due", en: "it's two o'clock" },
      { it: "e mezzo / mezza", en: "half past" },
      { it: "e un quarto", en: "quarter past" },
      { it: "meno un quarto", en: "quarter to" },
      { it: "di mattina", en: "in the morning" },
      { it: "di pomeriggio", en: "in the afternoon" },
      { it: "di sera", en: "in the evening" },
      { it: "ora", en: "hour / time", gender: "f" },
      { it: "minuto", en: "minute", gender: "m" },
    ],
    grammar: [
      {
        title: "È vs sono with clock times",
        explanation:
          "Use è l'una for 1:00. For other hours use sono le + number. Add e + minutes, e mezzo, or meno for 'to'.",
        examples: [
          { it: "È l'una.", en: "It's one o'clock." },
          { it: "Sono le tre e mezzo.", en: "It's half past three." },
          { it: "Sono le otto meno un quarto.", en: "It's a quarter to eight." },
        ],
      },
    ],
    dialogue: [
      {
        speaker: "Sara",
        it: "Scusa, che ora è?",
        en: "Excuse me, what time is it?",
      },
      {
        speaker: "Marco",
        it: "Sono le dieci e un quarto.",
        en: "It's a quarter past ten.",
      },
      {
        speaker: "Sara",
        it: "Grazie! A che ora è il treno?",
        en: "Thanks! What time is the train?",
      },
      {
        speaker: "Marco",
        it: "Alle undici di mattina.",
        en: "At eleven in the morning.",
      },
    ],
    exercises: [
      {
        id: "u2l2-1",
        type: "multiple-choice",
        prompt: "Ask «what time is it?»",
        options: ["che ora è?", "quanto costa?", "come stai?", "dove sei?"],
        answer: 0,
      },
      {
        id: "u2l2-2",
        type: "fill-blank",
        prompt: "It's one o'clock",
        sentence: "___ l'una.",
        answer: "È",
        accept: ["E", "è", "e"],
      },
      {
        id: "u2l2-3",
        type: "fill-blank",
        prompt: "It's two o'clock",
        sentence: "___ le due.",
        answer: "Sono",
        accept: ["sono"],
      },
      {
        id: "u2l2-4",
        type: "match",
        prompt: "Match time phrases",
        pairs: [
          { left: "di mattina", right: "in the morning" },
          { left: "di sera", right: "in the evening" },
          { left: "e mezzo", right: "half past" },
          { left: "meno un quarto", right: "quarter to" },
        ],
      },
      {
        id: "u2l2-5",
        type: "multiple-choice",
        prompt: "«Sono le cinque e mezzo» ≈",
        options: ["4:30", "5:00", "5:30", "6:15"],
        answer: 2,
      },
      {
        id: "u2l2-6",
        type: "fill-blank",
        prompt: "At seven (clock time)",
        sentence: "___ sette",
        answer: "Alle",
        accept: ["alle"],
      },
      {
        id: "u2l2-7",
        type: "multiple-choice",
        prompt: "«Di pomeriggio» means…",
        options: ["at night", "in the afternoon", "at noon", "tomorrow"],
        answer: 1,
      },
      {
        id: "u2l2-8",
        type: "reorder",
        prompt: "Order the dialogue",
        lines: [
          "Scusa, che ora è?",
          "Sono le dieci e un quarto.",
          "Grazie! A che ora è il treno?",
          "Alle undici di mattina.",
        ],
      },
    ],
  },
  {
    id: "u2-l3",
    unitId: "unit-2",
    number: 7,
    title: "Days & Calendar",
    titleIt: "I giorni",
    summary: "Name the days of the week and talk about today, tomorrow, and yesterday.",
    objectives: [
      "Name days of the week",
      "Use oggi, domani, ieri",
      "Say on Monday with di + day",
    ],
    vocabulary: [
      { it: "lunedì", en: "Monday" },
      { it: "martedì", en: "Tuesday" },
      { it: "mercoledì", en: "Wednesday" },
      { it: "giovedì", en: "Thursday" },
      { it: "venerdì", en: "Friday" },
      { it: "sabato", en: "Saturday" },
      { it: "domenica", en: "Sunday", gender: "f" },
      { it: "oggi", en: "today" },
      { it: "domani", en: "tomorrow" },
      { it: "ieri", en: "yesterday" },
      { it: "settimana", en: "week", gender: "f" },
      { it: "weekend / fine settimana", en: "weekend" },
    ],
    grammar: [
      {
        title: "Days without capitals",
        explanation:
          "Days of the week are not capitalized in Italian. Use di + day for 'on Monday': di lunedì. Domenica is feminine; the others are masculine.",
        examples: [
          { it: "Di lunedì lavoro.", en: "On Mondays I work." },
          { it: "Domenica riposo.", en: "On Sunday I rest." },
        ],
      },
    ],
    dialogue: [
      {
        speaker: "Elena",
        it: "Che giorno è oggi?",
        en: "What day is it today?",
      },
      {
        speaker: "Bruno",
        it: "Oggi è mercoledì.",
        en: "Today is Wednesday.",
      },
      {
        speaker: "Elena",
        it: "Domani è giovedì. Lavori?",
        en: "Tomorrow is Thursday. Are you working?",
      },
      {
        speaker: "Bruno",
        it: "Sì. Sabato e domenica no!",
        en: "Yes. Not Saturday and Sunday!",
      },
    ],
    exercises: [
      {
        id: "u2l3-1",
        type: "match",
        prompt: "Match the days",
        pairs: [
          { left: "lunedì", right: "Monday" },
          { left: "venerdì", right: "Friday" },
          { left: "sabato", right: "Saturday" },
          { left: "domenica", right: "Sunday" },
        ],
      },
      {
        id: "u2l3-2",
        type: "multiple-choice",
        prompt: "«Domani» means…",
        options: ["yesterday", "today", "tomorrow", "week"],
        answer: 2,
      },
      {
        id: "u2l3-3",
        type: "fill-blank",
        prompt: "Today is…",
        sentence: "___ è venerdì.",
        answer: "Oggi",
        accept: ["oggi"],
      },
      {
        id: "u2l3-4",
        type: "fill-blank",
        prompt: "Yesterday",
        sentence: "___ è stato lunedì.",
        answer: "Ieri",
        accept: ["ieri"],
      },
      {
        id: "u2l3-5",
        type: "multiple-choice",
        prompt: "Day after martedì?",
        options: ["lunedì", "mercoledì", "giovedì", "venerdì"],
        answer: 1,
      },
      {
        id: "u2l3-6",
        type: "multiple-choice",
        prompt: "«Di lunedì» means…",
        options: ["every day", "on Monday(s)", "last Monday", "Monday morning"],
        answer: 1,
      },
      {
        id: "u2l3-7",
        type: "fill-blank",
        prompt: "Week in Italian",
        sentence: "settimana = ___",
        answer: "week",
      },
      {
        id: "u2l3-8",
        type: "reorder",
        prompt: "Order the dialogue",
        lines: [
          "Che giorno è oggi?",
          "Oggi è mercoledì.",
          "Domani è giovedì. Lavori?",
          "Sì. Sabato e domenica no!",
        ],
      },
    ],
  },
  {
    id: "u2-l4",
    unitId: "unit-2",
    number: 8,
    title: "Food Basics",
    titleIt: "Il cibo",
    summary: "Essential food words and how to say what you like to eat and drink.",
    objectives: [
      "Name common foods and drinks",
      "Use mi piace / mi piacciono",
      "Order simply at a café",
    ],
    vocabulary: [
      { it: "pane", en: "bread", gender: "m" },
      { it: "acqua", en: "water", gender: "f" },
      { it: "caffè", en: "coffee", gender: "m" },
      { it: "vino", en: "wine", gender: "m" },
      { it: "pasta", en: "pasta", gender: "f" },
      { it: "pizza", en: "pizza", gender: "f" },
      { it: "formaggio", en: "cheese", gender: "m" },
      { it: "frutta", en: "fruit", gender: "f" },
      { it: "colazione", en: "breakfast", gender: "f" },
      { it: "pranzo", en: "lunch", gender: "m" },
      { it: "cena", en: "dinner", gender: "f" },
      { it: "mi piace", en: "I like (singular)" },
      { it: "mi piacciono", en: "I like (plural)" },
    ],
    grammar: [
      {
        title: "Mi piace / mi piacciono",
        explanation:
          "The thing liked is the grammatical subject. Use mi piace + singular noun/infinitive; mi piacciono + plural noun.",
        examples: [
          { it: "Mi piace la pizza.", en: "I like pizza." },
          { it: "Mi piacciono i caffè.", en: "I like coffees. (plural)" },
          { it: "Mi piace mangiare.", en: "I like to eat." },
        ],
      },
    ],
    dialogue: [
      {
        speaker: "Cameriere",
        it: "Buongiorno! Che cosa prende?",
        en: "Good morning! What will you have?",
      },
      {
        speaker: "Cliente",
        it: "Un caffè e un cornetto, per favore.",
        en: "A coffee and a croissant, please.",
      },
      {
        speaker: "Cameriere",
        it: "Subito!",
        en: "Right away!",
      },
      {
        speaker: "Cliente",
        it: "Grazie. Mi piace molto il caffè italiano!",
        en: "Thanks. I really like Italian coffee!",
      },
    ],
    exercises: [
      {
        id: "u2l4-1",
        type: "match",
        prompt: "Match food words",
        pairs: [
          { left: "pane", right: "bread" },
          { left: "acqua", right: "water" },
          { left: "cena", right: "dinner" },
          { left: "formaggio", right: "cheese" },
        ],
      },
      {
        id: "u2l4-2",
        type: "multiple-choice",
        prompt: "Breakfast in Italian:",
        options: ["pranzo", "cena", "colazione", "frutta"],
        answer: 2,
      },
      {
        id: "u2l4-3",
        type: "fill-blank",
        prompt: "I like pizza (singular)",
        sentence: "Mi ___ la pizza.",
        answer: "piace",
      },
      {
        id: "u2l4-4",
        type: "fill-blank",
        prompt: "I like apples (le mele — plural)",
        sentence: "Mi ___ le mele.",
        answer: "piacciono",
      },
      {
        id: "u2l4-5",
        type: "multiple-choice",
        prompt: "«Che cosa prende?» ≈",
        options: ["How much is it?", "What will you have?", "Where is it?", "Who are you?"],
        answer: 1,
      },
      {
        id: "u2l4-6",
        type: "fill-blank",
        prompt: "Coffee",
        sentence: "Un ___, per favore.",
        answer: "caffè",
        accept: ["caffe", "caffé"],
      },
      {
        id: "u2l4-7",
        type: "multiple-choice",
        prompt: "Lunch is…",
        options: ["colazione", "pranzo", "cena", "pane"],
        answer: 1,
      },
      {
        id: "u2l4-8",
        type: "reorder",
        prompt: "Order the café dialogue",
        lines: [
          "Buongiorno! Che cosa prende?",
          "Un caffè e un cornetto, per favore.",
          "Subito!",
          "Grazie. Mi piace molto il caffè italiano!",
        ],
      },
    ],
  },
];
