import type { Lesson } from "@/lib/types";

export const unit6Lessons: Lesson[] = [
  {
    id: "u6-l1",
    unitId: "unit-6",
    number: 21,
    title: "Passato Prossimo",
    titleIt: "Il passato prossimo",
    summary: "Talk about completed past actions with avere and essere + participle.",
    objectives: [
      "Form past participles of regular verbs",
      "Choose avere vs essere as auxiliaries",
      "Agree participles with essere",
    ],
    vocabulary: [
      { it: "ho mangiato", en: "I ate / I have eaten" },
      { it: "ho parlato", en: "I spoke" },
      { it: "ho preso", en: "I took / had" },
      { it: "sono andato/a", en: "I went" },
      { it: "sono arrivato/a", en: "I arrived" },
      { it: "ieri", en: "yesterday" },
      { it: "la settimana scorsa", en: "last week" },
      { it: "già", en: "already" },
      { it: "non ancora", en: "not yet" },
    ],
    grammar: [
      {
        title: "Avere + participle",
        explanation:
          "Most verbs take avere. Regular participles: -are → -ato, -ere → -uto, -ire → -ito. Some common irregulars: preso, fatto, detto, scritto, letto, visto.",
        examples: [
          { it: "Ho mangiato la pizza.", en: "I ate the pizza." },
          { it: "Hai visto Marco?", en: "Did you see Marco?" },
        ],
      },
      {
        title: "Essere + participle",
        explanation:
          "Verbs of movement/change and reflexives take essere. The participle agrees with the subject: sono andata (f.), sono andati (m pl).",
        examples: [
          { it: "Sono andata a Roma.", en: "I went to Rome (f)." },
          { it: "Siamo arrivati tardi.", en: "We arrived late." },
        ],
      },
    ],
    dialogue: [
      {
        speaker: "Lara",
        it: "Cosa hai fatto ieri?",
        en: "What did you do yesterday?",
      },
      {
        speaker: "Hugo",
        it: "Sono andato al museo e ho mangiato una pizza.",
        en: "I went to the museum and ate a pizza.",
      },
      {
        speaker: "Lara",
        it: "Bello! Hai visto la mostra nuova?",
        en: "Nice! Did you see the new exhibition?",
      },
      {
        speaker: "Hugo",
        it: "Sì, l'ho vista. È fantastica!",
        en: "Yes, I saw it. It's fantastic!",
      },
    ],
    exercises: [
      {
        id: "u6l1-1",
        type: "fill-blank",
        prompt: "I ate (avere)",
        sentence: "Ho ___.",
        answer: "mangiato",
      },
      {
        id: "u6l1-2",
        type: "fill-blank",
        prompt: "I went (m.)",
        sentence: "Sono ___.",
        answer: "andato",
      },
      {
        id: "u6l1-3",
        type: "multiple-choice",
        prompt: "Participle of parlare:",
        options: ["parluto", "parlato", "parlito", "parlendo"],
        answer: 1,
      },
      {
        id: "u6l1-4",
        type: "multiple-choice",
        prompt: "Which verb takes essere?",
        options: ["mangiare", "parlare", "andare", "prendere"],
        answer: 2,
      },
      {
        id: "u6l1-5",
        type: "match",
        prompt: "Match past phrases",
        pairs: [
          { left: "ho preso", right: "I took / had" },
          { left: "sono arrivata", right: "I arrived (f)" },
          { left: "già", right: "already" },
          { left: "non ancora", right: "not yet" },
        ],
      },
      {
        id: "u6l1-6",
        type: "fill-blank",
        prompt: "Did you see…? (tu)",
        sentence: "___ visto il film?",
        answer: "Hai",
        accept: ["hai"],
      },
      {
        id: "u6l1-7",
        type: "multiple-choice",
        prompt: "«La settimana scorsa» means…",
        options: ["next week", "last week", "this week", "every week"],
        answer: 1,
      },
      {
        id: "u6l1-8",
        type: "reorder",
        prompt: "Order the dialogue",
        lines: [
          "Cosa hai fatto ieri?",
          "Sono andato al museo e ho mangiato una pizza.",
          "Bello! Hai visto la mostra nuova?",
          "Sì, l'ho vista. È fantastica!",
        ],
      },
    ],
  },
  {
    id: "u6-l2",
    unitId: "unit-6",
    number: 22,
    title: "Near Future",
    titleIt: "Il futuro prossimo",
    summary: "Talk about plans with stare per and andare a + infinitive.",
    objectives: [
      "Use stare per + infinitive",
      "Use andare a + infinitive for plans",
      "Talk about domani and weekend plans",
    ],
    vocabulary: [
      { it: "sto per…", en: "I'm about to…" },
      { it: "vado a…", en: "I'm going to…" },
      { it: "domani", en: "tomorrow" },
      { it: "questa sera", en: "this evening" },
      { it: "il weekend prossimo", en: "next weekend" },
      { it: "progetto", en: "plan / project", gender: "m" },
      { it: "intenzione", en: "intention", gender: "f" },
      { it: "forse", en: "maybe" },
      { it: "sicuramente", en: "surely / definitely" },
    ],
    grammar: [
      {
        title: "Talking about the near future",
        explanation:
          "At A1, stare per + infinitive (about to) and andare a + infinitive (going to) cover most near-future needs. You can also use the present with a future time marker: Domani parto.",
        examples: [
          { it: "Sto per uscire.", en: "I'm about to go out." },
          { it: "Vado a studiare.", en: "I'm going to study." },
          { it: "Domani lavoro.", en: "Tomorrow I'm working." },
        ],
      },
    ],
    dialogue: [
      {
        speaker: "Bea",
        it: "Cosa fai questa sera?",
        en: "What are you doing this evening?",
      },
      {
        speaker: "Rocco",
        it: "Vado a cenare con degli amici. E tu?",
        en: "I'm going to have dinner with some friends. And you?",
      },
      {
        speaker: "Bea",
        it: "Sto per finire un progetto, poi forse esco.",
        en: "I'm about to finish a project, then maybe I'll go out.",
      },
      {
        speaker: "Rocco",
        it: "Perfetto. Domani ci vediamo?",
        en: "Perfect. Shall we see each other tomorrow?",
      },
    ],
    exercises: [
      {
        id: "u6l2-1",
        type: "fill-blank",
        prompt: "I'm about to…",
        sentence: "___ per partire.",
        answer: "Sto",
        accept: ["sto"],
      },
      {
        id: "u6l2-2",
        type: "fill-blank",
        prompt: "I'm going to study",
        sentence: "Vado a ___.",
        answer: "studiare",
      },
      {
        id: "u6l2-3",
        type: "match",
        prompt: "Match future phrases",
        pairs: [
          { left: "questa sera", right: "this evening" },
          { left: "forse", right: "maybe" },
          { left: "sicuramente", right: "definitely" },
          { left: "domani", right: "tomorrow" },
        ],
      },
      {
        id: "u6l2-4",
        type: "multiple-choice",
        prompt: "«Sto per uscire» means…",
        options: ["I went out", "I'm about to go out", "I want to go out", "I never go out"],
        answer: 1,
      },
      {
        id: "u6l2-5",
        type: "multiple-choice",
        prompt: "Ask about tonight's plans:",
        options: [
          "Cosa hai fatto ieri?",
          "Cosa fai questa sera?",
          "Dove sei?",
          "Quanto costa?",
        ],
        answer: 1,
      },
      {
        id: "u6l2-6",
        type: "fill-blank",
        prompt: "next weekend",
        sentence: "il weekend ___",
        answer: "prossimo",
      },
      {
        id: "u6l2-7",
        type: "fill-blank",
        prompt: "Shall we see each other?",
        sentence: "Ci ___?",
        answer: "vediamo",
      },
      {
        id: "u6l2-8",
        type: "reorder",
        prompt: "Order the dialogue",
        lines: [
          "Cosa fai questa sera?",
          "Vado a cenare con degli amici. E tu?",
          "Sto per finire un progetto, poi forse esco.",
          "Perfetto. Domani ci vediamo?",
        ],
      },
    ],
  },
  {
    id: "u6-l3",
    unitId: "unit-6",
    number: 23,
    title: "A1 Review",
    titleIt: "Ripasso",
    summary: "Review the core grammar and vocabulary from the whole course.",
    objectives: [
      "Revisit essere, avere, and present tense",
      "Review articles, adjectives, and prepositions",
      "Self-check A1 survival phrases",
    ],
    vocabulary: [
      { it: "ripasso", en: "review", gender: "m" },
      { it: "ricordare", en: "to remember" },
      { it: "dimenticare", en: "to forget" },
      { it: "utile", en: "useful" },
      { it: "importante", en: "important" },
      { it: "di nuovo", en: "again" },
      { it: "tutto chiaro?", en: "all clear?" },
      { it: "ancora una volta", en: "one more time" },
    ],
    grammar: [
      {
        title: "A1 checklist",
        explanation:
          "You can introduce yourself, talk about daily life, describe people and things, navigate town, shop, and speak about past and near-future events with simple forms.",
        examples: [
          { it: "Mi chiamo… e sono di…", en: "My name is… and I'm from…" },
          { it: "Ieri sono andato/a…", en: "Yesterday I went…" },
          { it: "Domani vado a…", en: "Tomorrow I'm going to…" },
        ],
      },
    ],
    dialogue: [
      {
        speaker: "Insegnante",
        it: "Tutto chiaro? Ricordi il passato prossimo?",
        en: "All clear? Do you remember the passato prossimo?",
      },
      {
        speaker: "Studente",
        it: "Sì! Ieri ho studiato e sono andato al mercato.",
        en: "Yes! Yesterday I studied and went to the market.",
      },
      {
        speaker: "Insegnante",
        it: "Bravo! E domani?",
        en: "Well done! And tomorrow?",
      },
      {
        speaker: "Studente",
        it: "Domani vado a ripassare di nuovo!",
        en: "Tomorrow I'm going to review again!",
      },
    ],
    exercises: [
      {
        id: "u6l3-1",
        type: "multiple-choice",
        prompt: "«Io ___ studente.»",
        options: ["sei", "sono", "è", "siamo"],
        answer: 1,
      },
      {
        id: "u6l3-2",
        type: "fill-blank",
        prompt: "I have (avere)",
        sentence: "___ un libro.",
        answer: "Ho",
        accept: ["ho"],
      },
      {
        id: "u6l3-3",
        type: "multiple-choice",
        prompt: "Definite article for «casa»:",
        options: ["il", "lo", "la", "i"],
        answer: 2,
      },
      {
        id: "u6l3-4",
        type: "fill-blank",
        prompt: "I like pizza",
        sentence: "Mi ___ la pizza.",
        answer: "piace",
      },
      {
        id: "u6l3-5",
        type: "match",
        prompt: "Quick review match",
        pairs: [
          { left: "buongiorno", right: "good morning" },
          { left: "dov'è", right: "where is" },
          { left: "quanto costa", right: "how much does it cost" },
          { left: "mi chiamo", right: "my name is" },
        ],
      },
      {
        id: "u6l3-6",
        type: "fill-blank",
        prompt: "I went (f.)",
        sentence: "Sono ___.",
        answer: "andata",
      },
      {
        id: "u6l3-7",
        type: "multiple-choice",
        prompt: "«Ancora una volta» means…",
        options: ["never again", "one more time", "already", "last time"],
        answer: 1,
      },
      {
        id: "u6l3-8",
        type: "reorder",
        prompt: "Order the review dialogue",
        lines: [
          "Tutto chiaro? Ricordi il passato prossimo?",
          "Sì! Ieri ho studiato e sono andato al mercato.",
          "Bravo! E domani?",
          "Domani vado a ripassare di nuovo!",
        ],
      },
    ],
  },
  {
    id: "u6-l4",
    unitId: "unit-6",
    number: 24,
    title: "Capstone Dialogue",
    titleIt: "Dialogo finale",
    summary:
      "Put it all together in a travel-day conversation: meeting, plans, food, and directions.",
    objectives: [
      "Follow a multi-turn real-world dialogue",
      "Reuse greetings, plans, food, and directions",
      "Finish A1 with a confident survival conversation",
    ],
    vocabulary: [
      { it: "benvenuto / benvenuta", en: "welcome (m/f)" },
      { it: "in ritardo", en: "late" },
      { it: "in orario", en: "on time" },
      { it: "biglietto", en: "ticket", gender: "m" },
      { it: "visita", en: "visit", gender: "f" },
      { it: "consiglio", en: "advice / tip", gender: "m" },
      { it: "assaggiare", en: "to taste / try (food)" },
      { it: "ci vediamo!", en: "see you!" },
    ],
    grammar: [
      {
        title: "Survival conversation tips",
        explanation:
          "Combine short clear sentences. Recycle known frames: Mi chiamo…, Vorrei…, Dov'è…?, Ieri ho…, Domani vado a…. Asking someone to repeat — Può ripetere, per favore? — is fair game.",
        examples: [
          { it: "Può ripetere, per favore?", en: "Can you repeat, please?" },
          { it: "Più lentamente, per favore.", en: "More slowly, please." },
        ],
      },
    ],
    dialogue: [
      {
        speaker: "Giulia",
        it: "Ciao! Benvenuto a Bologna. Come è andato il viaggio?",
        en: "Hi! Welcome to Bologna. How was the trip?",
      },
      {
        speaker: "Alex",
        it: "Bene, grazie! Il treno è arrivato in orario. Mi chiamo Alex.",
        en: "Good, thanks! The train arrived on time. My name is Alex.",
      },
      {
        speaker: "Giulia",
        it: "Piacere, Alex. Hai fame? Andiamo a mangiare una pizza?",
        en: "Nice to meet you, Alex. Are you hungry? Shall we go eat a pizza?",
      },
      {
        speaker: "Alex",
        it: "Sì, vorrei assaggiare la cucina locale. Dov'è un buon ristorante?",
        en: "Yes, I'd like to try the local food. Where is a good restaurant?",
      },
      {
        speaker: "Giulia",
        it: "È qui vicino. Poi domani andiamo a visitare il museo.",
        en: "It's nearby. Then tomorrow we're going to visit the museum.",
      },
      {
        speaker: "Alex",
        it: "Perfetto. Grazie per il consiglio!",
        en: "Perfect. Thanks for the tip!",
      },
    ],
    exercises: [
      {
        id: "u6l4-1",
        type: "multiple-choice",
        prompt: "«In orario» means…",
        options: ["late", "on time", "early", "canceled"],
        answer: 1,
      },
      {
        id: "u6l4-2",
        type: "fill-blank",
        prompt: "Welcome (to a man)",
        sentence: "___ a Bologna!",
        answer: "Benvenuto",
        accept: ["benvenuto"],
      },
      {
        id: "u6l4-3",
        type: "fill-blank",
        prompt: "I'd like to taste…",
        sentence: "Vorrei ___ la cucina locale.",
        answer: "assaggiare",
      },
      {
        id: "u6l4-4",
        type: "match",
        prompt: "Capstone vocabulary",
        pairs: [
          { left: "biglietto", right: "ticket" },
          { left: "consiglio", right: "advice / tip" },
          { left: "in ritardo", right: "late" },
          { left: "ci vediamo", right: "see you" },
        ],
      },
      {
        id: "u6l4-5",
        type: "multiple-choice",
        prompt: "Ask someone to repeat:",
        options: [
          "Quanto costa?",
          "Può ripetere, per favore?",
          "Dove abiti?",
          "Che ora è?",
        ],
        answer: 1,
      },
      {
        id: "u6l4-6",
        type: "fill-blank",
        prompt: "Where is a good restaurant?",
        sentence: "___ un buon ristorante?",
        answer: "Dov'è",
        accept: ["Dove è", "dov'è", "dove è"],
      },
      {
        id: "u6l4-7",
        type: "multiple-choice",
        prompt: "«Grazie per il consiglio» means…",
        options: [
          "Thanks for the food",
          "Thanks for the tip",
          "Thanks for the ticket",
          "Thanks for coming",
        ],
        answer: 1,
      },
      {
        id: "u6l4-8",
        type: "reorder",
        prompt: "Order the opening of the capstone dialogue",
        lines: [
          "Ciao! Benvenuto a Bologna. Come è andato il viaggio?",
          "Bene, grazie! Il treno è arrivato in orario. Mi chiamo Alex.",
          "Piacere, Alex. Hai fame? Andiamo a mangiare una pizza?",
          "Sì, vorrei assaggiare la cucina locale. Dov'è un buon ristorante?",
        ],
      },
      {
        id: "u6l4-9",
        type: "multiple-choice",
        prompt: "Tomorrow they will…",
        options: ["buy a ticket", "visit the museum", "take a train", "go home"],
        answer: 1,
        explanation: "Giulia says: Poi domani andiamo a visitare il museo.",
      },
      {
        id: "u6l4-10",
        type: "fill-blank",
        prompt: "See you!",
        sentence: "Ci ___!",
        answer: "vediamo",
      },
    ],
  },
];
